apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: mynode-app
  ports:
    - targetPort: 3000
      port: 80
      nodePort: 30001
